<a href="https://colab.research.google.com/github/Preciousdisono/Keziah_IS3/blob/main/Activity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [37]:
import pandas as pd

In [38]:
df = pd.read_csv('https://raw.githubusercontent.com/Preciousdisono/Keziah_IS3/refs/heads/main/student%20performace.csv')

In [39]:
df.head(50)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,NaN,3,1,91
1,4,82,No,4,2,65
2,8,51,Yes,7,2,45
3,5,52,NaN,5,2,36
4,7,75,No,1,5,66
5,3,78,No,9,6,61
6,7,73,Yes,5,6,63
7,8,45,NaN,4,6,42
8,5,77,No,8,2,61
9,4,89,No,4,0,69
10,8,91,No,4,5,84
11,8,79,NaN,6,2,73
12,3,47,No,9,2,27
13,6,47,No,5,2,33
14,5,79,NaN,7,8,68
15,2,72,No,4,3,43
16,8,73,Yes,8,4,67
17,6,83,Yes,7,2,70
18,2,54,NaN,8,9,30
19,5,75,No,7,0,63
20,1,99,Yes,4,3,71
21,6,96,No,9,0,85
22,9,74,NaN,5,6,73
23,1,85,No,5,6,57
24,3,61,No,6,3,35
25,7,62,Yes,7,4,49
26,4,79,NaN,8,9,66
27,9,84,Yes,6,6,83
28,3,94,Yes,6,5,74
29,5,90,Yes,4,3,74
30,3,61,Yes,7,3,39
31,7,44,NaN,9,1,36
32,5,70,Yes,6,9,58
33,9,52,Yes,8,1,47
34,7,67,Yes,9,3,60
35,2,97,Yes,9,4,74
36,4,59,No,8,3,42
37,9,72,No,8,2,68
38,2,55,Yes,4,1,32
39,9,68,No,5,3,64
40,5,62,No,7,4,45
41,2,63,Yes,6,0,39
42,4,73,NaN,7,0,58
43,7,46,No,9,5,36
44,8,77,Yes,6,4,71
45,4,68,Yes,7,4,53
46,7,67,No,7,5,52
47,4,67,NaN,8,3,54
48,2,66,Yes,7,3,53
49,5,77,Yes,6,4,67

In [40]:
df_filna = df.fillna('N/A')

In [41]:
df_filna.head(50)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,N/A,3,1,91
1,4,82,No,4,2,65
2,8,51,Yes,7,2,45
3,5,52,N/A,5,2,36
4,7,75,No,1,5,66
5,3,78,No,9,6,61
6,7,73,Yes,5,6,63
7,8,45,N/A,4,6,42
8,5,77,No,8,2,61
9,4,89,No,4,0,69
10,8,91,No,4,5,84
11,8,79,N/A,6,2,73
12,3,47,No,9,2,27
13,6,47,No,5,2,33
14,5,79,N/A,7,8,68
15,2,72,No,4,3,43
16,8,73,Yes,8,4,67
17,6,83,Yes,7,2,70
18,2,54,N/A,8,9,30
19,5,75,No,7,0,63
20,1,99,Yes,4,3,71
21,6,96,No,9,0,85
22,9,74,N/A,5,6,73
23,1,85,No,5,6,57
24,3,61,No,6,3,35
25,7,62,Yes,7,4,49
26,4,79,N/A,8,9,66
27,9,84,Yes,6,6,83
28,3,94,Yes,6,5,74
29,5,90,Yes,4,3,74
30,3,61,Yes,7,3,39
31,7,44,N/A,9,1,36
32,5,70,Yes,6,9,58
33,9,52,Yes,8,1,47
34,7,67,Yes,9,3,60
35,2,97,Yes,9,4,74
36,4,59,No,8,3,42
37,9,72,No,8,2,68
38,2,55,Yes,4,1,32
39,9,68,No,5,3,64
40,5,62,No,7,4,45
41,2,63,Yes,6,0,39
42,4,73,N/A,7,0,58
43,7,46,No,9,5,36
44,8,77,Yes,6,4,71
45,4,68,Yes,7,4,53
46,7,67,No,7,5,52
47,4,67,N/A,8,3,54
48,2,66,Yes,7,3,53
49,5,77,Yes,6,4,67

In [42]:
(df.isnull().sum())

Hours Studied                        0
Previous Scores                      0
Extracurricular Activities          11
Sleep Hours                          0
Sample Question Papers Practiced     0
Performance Index                    0
dtype: int64

In [43]:
df = df.drop(columns=['Extracurricular Activities'])

In [44]:
df.head(50)

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,3,1,91
1,4,82,4,2,65
2,8,51,7,2,45
3,5,52,5,2,36
4,7,75,1,5,66
5,3,78,9,6,61
6,7,73,5,6,63
7,8,45,4,6,42
8,5,77,8,2,61
9,4,89,4,0,69
10,8,91,4,5,84
11,8,79,6,2,73
12,3,47,9,2,27
13,6,47,5,2,33
14,5,79,7,8,68
15,2,72,4,3,43
16,8,73,8,4,67
17,6,83,7,2,70
18,2,54,8,9,30
19,5,75,7,0,63
20,1,99,4,3,71
21,6,96,9,0,85
22,9,74,5,6,73
23,1,85,5,6,57
24,3,61,6,3,35
25,7,62,7,4,49
26,4,79,8,9,66
27,9,84,6,6,83
28,3,94,6,5,74
29,5,90,4,3,74
30,3,61,7,3,39
31,7,44,9,1,36
32,5,70,6,9,58
33,9,52,8,1,47
34,7,67,9,3,60
35,2,97,9,4,74
36,4,59,8,3,42
37,9,72,8,2,68
38,2,55,4,1,32
39,9,68,5,3,64
40,5,62,7,4,45
41,2,63,6,0,39
42,4,73,7,0,58
43,7,46,9,5,36
44,8,77,6,4,71
45,4,68,7,4,53
46,7,67,7,5,52
47,4,67,8,3,54
48,2,66,7,3,53
49,5,77,6,4,67